### ISSUE TITLE
Update docs to include version(s) of Chef

### ISSUE THREAD

**Issue by emmajane** [msonnabaum/chef-drush#30]
Hey folks! I was going to submit a pull request, but it wasn't as straight forward as I was hoping. Ubuntu does ship with apt packages for Chef, but it's an older version Chef 10.12). This doesn't work with the latest version of the repo. If I update Chef to the latest on the server using omnibus (Chef v11.8.2), I get Console_Table errors and have to include at least half a dozen other cookbooks which don't get used (iis, windows, yum, yum-repl, xml, ...). I thought I had things working with the latest version of Chef 10.30.2, but after destroying the box and calling vagrant up again it's not working. :(

I'm wondering if the docs could be updated to give specific versions of Chef + php cookbook?

In case it's useful, here are some of the messages:

10.12.0 (default in ubuntu; doesn't work):
https://gist.github.com/emmajane/1186b6d400e9b842f49d

11.8.2 (latest Chef; doesn't work probably isn't working because of Chef-related reasons):
https://gist.github.com/emmajane/945f0027963a6d55c0b5 (note the IIS requirement...even if i resolve all of these extra dependencies, I still end up with missing Console_Table errors)

10.30.2 (latest 10x Chef)
https://gist.github.com/emmajane/ebf0f52e8190a5650bf3
(which I'm sure _did_ work once, but I can't get it to work now)

**Comment by walkah** [comment]
@emmajane can you test master now for me and confirm the Console_Table issues are fixed? Thanks!

**Comment by emmdel** [comment]
Hi,

I can confirm that using the `master` branch with Chef 11.4.2, the following Console_Table error is solved:

```
================================================================================
Error executing action `install` on resource 'php_pear[Console_Table]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
" | pecl -d preferred_state=stable install -a Console_Table ----
STDOUT: No releases available for package "pecl.php.net/Console_Table"
install failed
STDERR: 
" | pecl -d preferred_state=stable install -a Console_Table ----
" | pecl -d preferred_state=stable install -a Console_Table returned 1
```

**Comment by patcon** [comment]
Yeah, just ran into this and was wondering if I was crazy-town :)

**Comment by emmajane** [comment]
Unfortunately this is still failing for me with the default package for Chef in Ubuntu. 10.12.0. Not sure if it's because of Chef being too old, or because of the recipe being not right. https://gist.github.com/emmajane/9048437 (output after running vagrant destroy + vagrant up) If a newer version of Chef is required...what is the minimum requirement, and is this documented...I can definitely give it a try once I know which version I should be using.

**Comment by walkah** [comment]
@emmajane my testing has all been with 11.8 ... I'll look into adding 10.x to test-kitchen. that's a different error there (looks like the channel discovery isn't happening?).

**Comment by emmajane** [comment]
The Internet here is pretty sketchy. I'll try again once I'm back to the 
booming bandwidth of rural Canada. :/

James Walker wrote:

**Comment by emmajane** [comment]
Back at home now with a more reliable internet connection. I'm getting errors as follows in 10.30.2: https://gist.github.com/emmajane/9218861

**Comment by walkah** [comment]
Okay @emmajane I think this is finally working now :)
